streamauth/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('streamauthapp.urls'))
]

streamauthapp/urls.py
from django.urls import path
from django.conf.urls import include
from streamauthapp import views
from django.contrib.auth import views as auth_views
from .views import *

app_name = "streamauthapp"

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', login, name='login'),
    path('register/', register_user, name="register"),
    path('accounts/logout/', logout_user, name='logout'),
    path('accounts/user_login/', user_login, name='user_login'),
    path('', home, name='home'),
    path('events/', event_list, name='events'),
    path('events/form/', event_form, name='event_form'),
    path('events/<int:event_id>/', event_details, name='event'),
    path('form/<int:event_id>', event_details, name='event_details'),
    path('stream/<int:event_id>/', stream_details, name='stream'),
    path('login/stream/', user_login, name='stream_login'),
]

streamauthapp/models.py
from django.db import models

# Create your models here.

streamauthapp/models/event.py
from django.db import models
from django.contrib.auth.models import User

class StreamEvent(models.Model):
  
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, default=None, blank=True, null=True)
    stream_embed = models.CharField(max_length=1000)
    chat_feed = models.CharField(max_length=1000, default=None, blank=True, null=True)
    backgroundIMG = models.CharField(max_length=1000, default=None, blank=True, null=True)
    deleted = models.BooleanField(default=False)

streamauthapp/views.py
from django.shortcuts import render

# Create your views here.

streamauthapp/views/home.py
from django.shortcuts import render


def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

streamauthapp/views/user_login.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required

def user_login(request):
    if request.method == 'GET':
        template = 'viewer_login.html'
        context = {}

        return render(request, template, context)

streamauthapp/templates/events/detail.html
{% extends 'shared/base.html' %} 
{% block content %}
<h1>Event</h1>


<!-- Form Section for main project details imported from formSections -->
{% include "formSections/eventInfo.html" %}


{% endblock %}

streamauthapp/templates/events/list.html
{% extends 'shared/base.html' %} {% block content %}

<h1>Events List</h1>

<section class="eventList mt-2">
  {% for event in all_events %}
  <div class="card event-width">
    <div class="card-body m-4">
      <h4 class="card-title">Event Title: {{ event.name }}</h4>

      <h6 class="card-subtitle mb-2 text-muted">
        Description: {{ event.description }}
      </h6>
      <br>
      <div class="card-subtitle mb-2 text-muted">
        Embed Code: <input class="form-control" type="text" value='{{ event.stream_embed}}'>
      </div>
      <br>
      <div class="card-subtitle mb-2 text-muted">
        Chat Code: <input class="form-control" type="text" value='{{ event.chat_feed}}'>
      </div>

    <div class="container mx-0">
      <div class="d-flex justify-content-start">
        <form
          action="{% url 'streamauthapp:event_details' event.id %}"
          method="GET"
        >
          {% csrf_token %}
          <button class="btn btn-primary m-2">Edit</button>
        </form>

        <form
          action="{% url 'streamauthapp:stream' event.id %}"
          method="GET"
          target="_blank"
        >
          {% csrf_token %}
          <button class="btn btn-primary m-2">Stream View</button>
        </form>

        <form
          action="{% url 'streamauthapp:event' event.id %}"
          method="POST"
        >
          {% csrf_token %}
          <input type="hidden" name="actual_method" value="ARCHIVE" />
          <button class="btn btn-danger m-2">{% if event.deleted is not None %} Archive {% else %} Delete {% endif %}</button>
        </form>

      </div>
    </div>
  </div>
  {% endfor %}
</section>
{% endblock %}

streamauthapp/templates/formSections/eventInfo.html
<div class="card-body">
  {% if event.id is not None %}
      <form id="eventForm" action="{% url 'streamauthapp:event' event.id %}" method="post">
  {% else %}
      <form id="eventForm" action="{% url 'streamauthapp:events' %}" method="post">
  {% endif %}
      {% csrf_token %}
      <div class="form-group">
          <label for="name">Name: </label>
          <input class="form-control" id="name" type="text" name="name" value="{{ event.name }}">
      </div>
      <div class="form-group">
          <label for="description">Description: </label>
          <input class="form-control" id="description" type="text" name="description" value="{{ event.description }}">
      </div>
      <div class="form-group">
          <label for="stream_embed">Steam Embed: </label>
          <input class="form-control" id="stream_embed" type="text" name="stream_embed" value="{{ event.stream_embed }}">
      </div>
      <div class="form-group">
          <label for="chat_feed">Chat Embed: </label>
          <input class="form-control" id="chat_feed" type="text" name="chat_feed" value="{{ event.chat_feed }}">
      </div>
      <div class="form-group">
        <label for="backgroundIMG">Background Image URL: </label>
        <input class="form-control" id="backgroundIMG" type="text" name="backgroundIMG" value="{{ event.backgroundIMG }}">
    </div>

      {% if event.id is not None %}
          <input type="hidden" name="actual_method" value="PUT">
          <button type="submit" value="Update">Update Details</button>
      {% else %}
      <button type="submit" >Save Details</button>
      {% endif %}

  </form>
  </div>

  

streamauthapp/templates/home.html
{% extends 'shared/base.html' %} 

{% block content %}
<h1>
  
</h1>
{% endblock content %}

streamauthapp/templates/index4.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="style4.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Bootstrap Sidebar</h3>
                <strong>BS</strong>
            </div>

            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-home"></i>
                        Home
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home 1</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-briefcase"></i>
                        About
                    </a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-copy"></i>
                        Pages
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-image"></i>
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-question"></i>
                        FAQ
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-paper-plane"></i>
                        Contact
                    </a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <h2>Collapsible Sidebar Using Bootstrap 4</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h2>Lorem Ipsum Dolor</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h2>Lorem Ipsum Dolor</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h3>Lorem Ipsum Dolor</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>

</html>

streamauthapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Stream Auth</title>

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
      integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="{% static 'css/base.css' %}"
      type="text/css"
      media="screen"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/login.css' %}"
      type="text/css"
      media="screen"
    />

    {% block css %} {% endblock %}
  </head>

  <body>
    <div class="wrapper">
      <!-- Sidebar  -->
      <nav id="sidebar">
        <div class="sidebar-header">
          {% if request.user.is_authenticated %}
          <h3>Hello, {{request.user.first_name}}</h3>
          {% else %}
          <h3>Welcome Guest</h3>
          {% endif %}
          <!-- <h3>Event Dashboard</h3>
          <strong>SA</strong> -->
        </div>

        <ul class="list-unstyled components">
          <li class="active">
            <a
              href="#homeSubmenu"
              data-toggle="collapse"
              aria-expanded="false"
              class="dropdown-toggle"
            >
              <i class="fas fa-home"></i>
              Account Info
            </a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
              <li>
                <a href="#">Home 1</a>
              </li>
              <li>
                <a href="#">Home 2</a>
              </li>
              <li>
                <a href="#">Home 3</a>
              </li>
            </ul>
          </li>
          <li>
            <a href="#">
              <i class="fas fa-briefcase"></i>
              About
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fas fa-image"></i>
              Users
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fas fa-question"></i>
              FAQ
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fas fa-paper-plane"></i>
              Customer Support
            </a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'streamauthapp:events' %}"
              >ALL EVENTS</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'streamauthapp:logout' %}"
              >LOGOUT</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'streamauthapp:login' %}">LOGIN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'streamauthapp:register' %}"
              >REGISTER</a
            >
          </li>
          {% endif %}
        </ul>

        <ul class="list-unstyled CTAs">
          <li>
            <a
              href="https://bootstrapious.com/tutorial/files/sidebar.zip"
              class="download"
              >Create Event</a
            >
          </li>
        </ul>
      </nav>

      <!-- Page Content  -->
      <div id="content">
        <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <button type="button" id="sidebarCollapse" class="btn btn-info">
              <i class="fas fa-align-left"></i>
              <span>Toggle Sidebar</span>
            </button>
            <button
              class="btn btn-dark d-inline-block d-lg-none ml-auto"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-align-justify">Test</i>
            </button>
          </div>
        </nav> -->
        <main>{% block content %} {% endblock %}</main>
      </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <!-- Popper.JS -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
      integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
      crossorigin="anonymous"
    ></script>
    <!-- Bootstrap JS -->
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
      integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
      crossorigin="anonymous"
    ></script>

    <script type="text/javascript">
      $(document).ready(function () {
        $("#sidebarCollapse").on("click", function () {
          $("#sidebar").toggleClass("active");
        });
      });
    </script>
  </body>
</html>

streamauthapp/templates/shared/streamview.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Stream Auth</title>

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
      integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="{% static 'css/base.css' %}"
      type="text/css"
      media="screen"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/login.css' %}"
      type="text/css"
      media="screen"
    />

    {% block css %} {% endblock %}
  </head>

  <body>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

streamauthapp/templates/streamview/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{{stream.name}}</title>

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
      integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="{% static 'css/base.css' %}"
      type="text/css"
      media="screen"
    />
    <link
      rel="stylesheet"
      href="{% static 'styles/login.css' %}"
      type="text/css"
      media="screen"
    />

    {% block css %} {% endblock %}
  </head>

  <body style="background-image: url({{stream.backgroundIMG}}); -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;">
    <main>
      <h2 class="text-center m-3" style="background-color: white;">{{stream.name}}</h2>
      <br><br>
      <br><br>
      <div class="row m-0 align-bottom">
        <div class="col-7 ml-4">
          <style>
            .embed-container {
              position: relative;
              padding-bottom: 56.25%;
              height: 0;
              overflow: hidden;
              max-width: 100%;
              height: auto;
            }
            .embed-container iframe,
            .embed-container object,
            .embed-container embed {
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              height: 100%;
            }
          </style>
          <div class="embed-container">{{stream.stream_embed|safe}}</div>
        </div>

        <div class="col-4 ml-4">{{stream.chat_feed|safe}}</div>
      </div>
    </main>
  </body>
</html>

streamauthapp/templates/viewer_login.html
{% extends 'shared/streamview.html' %} {% block content %}

<div class="loginFrom">
    <div id="logreg-forms">
        <h2>User Login</h2>
        <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
            <button class="btn btn-danger" type="submit">Login</button>
            <br><br>
            <h6>Sign up</h6>
            <a class="btn btn-primary" href="{% url 'streamauthapp:register' %}">REGISTER</a>
        </form>
    </div>
</div>
{% endblock %}